### ISSUE TITLE
Tokenizer fails on windows

### ISSUE THREAD

**Issue by SaptakBhoumik** [peregrine-lang/Peregrine#44]

**Comment by Jammin-Coder** [comment]
Could it be because the Windows newline character is different than that of the OSX/Unix-like systems?
The Windows escape sequence for newlines is `\r\n`, but in `tokenizer.v` all of the newline characters are just `\n`.
Perhaps if we added a check to see which OS Peregrine is running on and then changed the newline character based on the result of the check. I'm not 100% sure if that would solve it, though it's worth a shot.

I would try it myself but I was having trouble setting up GCC in Windows so I can't test it.

**Comment by SaptakBhoumik** [comment]
But for some people it is working on windows but not working for others

**Comment by Jammin-Coder** [comment]
Do different text editors save files with varying newline characters?
